name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: jenkins
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image arm64
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        # push: ${{ startsWith(github.ref, 'refs/tags/') }}
        push: true
        platforms: linux/arm64
        tags: scrolltech/l2geth:${{github.ref_name}}
        # cache-from: type=gha,scope=${{ github.workflow }}
        # cache-to: type=gha,scope=${{ github.workflow }}
